spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_education_portal
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use "validate" when schema is stable
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis

  flyway:
    enabled: false
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/smart_education_portal
    user: postgres
    password: password
    validateOnMigrate: false
    ignoreMissingMigrations: true
    # this line forces Flyway to accept unknown Postgres versions
    database:
      type: postgresql

# JWT settings
app:
  jwt:
    secret: change-this-to-a-very-long-random-secret-that-you-store-safe
    expiration-ms: 3600000  # 1 hour